apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "15"
  name: {{ .Values.sonarr.sonarr.fullnameOverride }}-api
spec:
  rules:
    - host: nickflix.io
      http:
        paths:
          - path: /{{ .Values.sonarr.sonarr.fullnameOverride }}/api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.sonarr.sonarr.fullnameOverride }}
                port:
                  number: 8989

  tls:
    - hosts: [nickflix.io]
      secretName: nickflix-io
