sonarr:
  sonarr:
    fullnameOverride: "sonarr4k"
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.priority: "15"
      hosts:
        - host: nickflix.io
          paths:
            - /sonarr4k