arr:
  fullnameOverride: "sonarr4k"
  ingress:
    annotations:
      traefik.ingress.kubernetes.io/router.priority: "15"
    hosts:
      - host: nickflix.io
        paths:
          - /sonarr4k

raw:
  resources:
    - apiVersion: networking.k8s.io/v1beta1
      kind: Ingress
      metadata:
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.priority: "20"
          traefik.ingress.kubernetes.io/router.tls: "true"
        name: sonarr4k-api
      spec:
        rules:
          - host: nickflix.io
            http:
              paths:
                - backend:
                    serviceName: sonarr4k
                    servicePort: 8989
                  path: /sonarr4k/api
        tls:
          - hosts:
              - nickflix.io
            secretName: nickflix-io