sonarr:
  sonarr:
    fullnameOverride: "sonarr"
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.priority: "10"
      hosts:
        - host: nickflix.io
          paths:
            - /sonarr