apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli
spec:
  replicas: 1
  serviceName: tautulli
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      nodeSelector:
        cajun.pro/cluster-gen: "2"
      restartPolicy: Always
      containers:
      - name: tautulli
        image: tautulli/tautulli:v2.5.3
        ports:
          - containerPort: 8181
        volumeMounts:
          - mountPath: /config
            name: config
      volumes:
        - name: config
          nfs:
            server: 10.0.10.211
            path: /mnt/nfs/tautulli
