tautulli:
  tautulli:
    image:
      tag: v2.5.5
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-4@kubernetescrd
      hosts:
        - host: nickflix.io
          paths:
            - /tautulli
      tls:
        - hosts: [nickflix.io]
          secretName: nickflix-io
      extraIngresses:
        - enabled: true
          nameSuffix: "api"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.priority: "15"
          hosts:
            - host: nickflix.io
              paths:
                - /tautulli/api
          tls:
            - hosts: [nickflix.io]
              secretName: nickflix-io
    persistence:
      type: statefulset
      config:
        accessMode: ReadWriteMany
        size: 10Gi
        storageClass: rook-cephfs
    nodeSelector:
      cajun.pro/cluster-gen: "2"
