apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: le-production
  labels:
    app: plex
  name: plex
spec:
  rules:
    - host: plex.cajun.pro
      http:
        paths:
          - backend:
              serviceName: plex
              servicePort: 32400
            path: /
  tls:
    - hosts:
        - plex.cajun.pro
      secretName: plex-cajun-pro
