apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: organizr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizr
  serviceName: organizr
  template:
    metadata:
      labels:
        app: organizr
    spec:
      nodeSelector:
        cajun.pro/cluster-gen: "2"
      restartPolicy: Always
      containers:
      - name: organizr
        image: organizrtools/organizr-v2:dev-latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        livenessProbe:
          failureThreshold: 10000
          httpGet:
            path: /
            port: 80
        volumeMounts:
          - mountPath: /config
            name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: organizr