apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "15"
  name: tautulli-api
spec:
  rules:
    - host: nickflix.io
      http:
        paths:
          - path: /tautulli/api
            pathType: Prefix
            backend:
              service:
                name: tautulli
                port:
                  number: 8181
  tls:
    - hosts: [nickflix.io]
      secretName: nickflix-io
