statping:
  image:
    tag: v0.90.69
  fullnameOverride: statping
  statping:
    name: cajun.pro status
    description: cajun.pro hosting status page
    domain: https://status.cajun.pro
    admin:
      existingSecret:
        enabled: true
        name: statping
  persistence:
    enabled: true
  postgres:
    enabled: true
    type: kubedb
    kubedb:
      enabled: true
      version: '11.1'
    posgresql:
      enabled: false
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - host: status.cajun.pro
        paths: [/]
    tls:
      - hosts:
          - status.cajun.pro
        secretName: status-cajun-pro
  externalSecret:
    enabled: true
    type: kubernetes-external-secrets
    kubernetesExternalSecrets:
      spec:
        backendType: vault
        vaultMountPoint: kubernetes-do
        vaultRole: vault-auth
      data:
        - name: admin-user
          key: kv-v2/data/auth/statping
          property: admin-user
        - name: admin-password
          key: kv-v2/data/auth/statping
          property: admin-password
        - name: admin-email
          key: kv-v2/data/auth/common
          property: email
  resources:
    requests:
     cpu: 100m
     memory: 128Mi
