apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "15"
  name: {{ .Values.radarr.radarr.fullnameOverride }}-api
spec:
  rules:
    - host: nickflix.io
      http:
        paths:
          - backend:
              serviceName: {{ .Values.radarr.radarr.fullnameOverride }}
              servicePort: 7878
            path: /{{ .Values.radarr.radarr.fullnameOverride }}/api
  tls:
    - hosts:
        - nickflix.io
      secretName: nickflix-io
