apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: bookstack
spec:
  backendType: vault
  vaultMountPoint: kubernetes-do
  vaultRole: vault-auth
  data:
    - name: temp-env
      key: kv-v2/data/auth/bookstack
      property: temp-env
    - name: user
      key: kv-v2/data/auth/bookstack
      property: db_user
    - name: password
      key: kv-v2/data/auth/bookstack
      property: db_password
