apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-bookstack
  namespace: cajun-pro
spec:
  version: "8.0.14"
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
