name: traefik
apiVersion: v2
version: 1.0.0
dependencies:
  - name: traefik
    version: 8.13.2
    repository: https://containous.github.io/traefik-helm-chart
  - name: traefik-forward-auth
    version: 1.0.1
    repository: https://k8s-at-home.com/charts/
    alias: tfa
