global:
  cluster: do

traefik:
  deployment:
    replicas: 2
  additionalArguments:
    - "--providers.kubernetesingress.ingressendpoint.publishedservice=kube-system/traefik"
    - "--providers.kubernetesingress.ingressendpoint.hostname=traefik-do.k8s.cajun.pro"
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-name: "traefik"

tfa:
  traefikForwardAuth:
    authHost: cajun.pro
  ingress:
    hosts:
      - host: cajun.pro
        paths:
          - /_oauth
    tls:
      - hosts:
          - cajun.pro
        secretName: cajun-pro