global:
  cluster: home

traefik:
  additionalArguments:
    - "--providers.kubernetesingress.ingressendpoint.hostname=traefik-home.k8s.cajun.pro"
    - "--providers.kubernetesingress.ingressendpoint.ip=12.161.64.36"
  service:
    externalIPs:
      - 172.30.0.10
  nodeSelector:
    cajun.pro/cluster-gen: "2"
  ingressRoute:
    dashboard:
      enabled: false

tfa:
  traefikForwardAuth:
    authHost: nickflix.io
  ingress:
    hosts:
      - host: nickflix.io
        paths:
          - /_oauth
    tls:
      - hosts:
          - nickflix.io
        secretName: nickflix-io
  nodeSelector:
    cajun.pro/cluster-gen: "2"