grafana:
  image:
    tag: 7.1.0
  nodeSelector:
    cajun.pro/cluster-gen: "2"
  persistence:
    enabled: true
    accessModes:
      - ReadWriteMany
  grafana.ini:
    server:
      root_url: https://grafana.cajun.pro
  plugins:
    - grafana-piechart-panel
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "10"
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: le-production
    hosts:
      - grafana.cajun.pro
    tls:
      - hosts:
          - grafana.cajun.pro
        secretName: grafana-cajun-pro