raw:
  resources:
    - apiVersion: kubernetes-client.io/v1
      kind: ExternalSecret
      metadata:
        name: aws-creds
      spec:
        backendType: vault
        vaultMountPoint: kubernetes-home
        vaultRole: vault-auth
        data:
          - name: credentials
            key: kv-v2/data/auth/aws-creds-file
            property: credentials
