radarr:
  radarr:
    fullnameOverride: "radarr"
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.priority: "10"
      hosts:
        - host: nickflix.io
          paths: [/radarr]
