arr:
  fullnameOverride: "radarr"
  ingress:
    annotations:
      traefik.ingress.kubernetes.io/router.priority: "10"
    hosts:
      - host: nickflix.io
        paths:
          - /radarr

raw:
  resources:
    - apiVersion: networking.k8s.io/v1beta1
      kind: Ingress
      metadata:
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.priority: "15"
          traefik.ingress.kubernetes.io/router.tls: "true"
        name: radarr-api
      spec:
        rules:
          - host: nickflix.io
            http:
              paths:
                - backend:
                    serviceName: radarr
                    servicePort: 7878
                  path: /radarr/api
        tls:
          - hosts:
              - nickflix.io
            secretName: nickflix-io