apiVersion: apps/v1
kind: Deployment
metadata:
  name: haste-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haste-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: haste-server
    spec:
      restartPolicy: Always
      containers:
      - name: haste-server
        image: dirtycajunrice/haste-server
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "npm install redis && /usr/bin/node /app/server.js"]
        ports:
          - containerPort: 7777
        livenessProbe:
          failureThreshold: 10000
          httpGet:
            path: /
            port: 7777
        volumeMounts:
          - mountPath: /app/config.js
            subPath: config.js
            name: config-js
      volumes:
        - name: config-js
          configMap:
            name: haste-files
            items:
            - key: config.js
              path: config.js
              mode: 0777
