apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-haste-server
  namespace: cajun-pro
spec:
  version: "5.0.3-v1"
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
