apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.tfa.fullnameOverride }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes-{{ .Values.global.cluster }}
  vaultRole: vault-auth
  data:
    - name: google-client-id
      key: kv-v2/data/auth/{{ .Values.tfa.fullnameOverride }}
      property: google-client-id
    - name: google-client-secret
      key: kv-v2/data/auth/{{ .Values.tfa.fullnameOverride }}
      property: google-client-secret
    - name: secret
      key: kv-v2/data/auth/{{ .Values.tfa.fullnameOverride }}
      property: secret
    - name: whitelist
      key: kv-v2/data/auth/{{ .Values.tfa.fullnameOverride }}
      property: whitelist