{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  annotations:

    cert-manager.io/cluster-issuer: le-production
  name: {{ .Values.traefik.fullnameOverride }}
spec:
  rules:
    - host: {{ include "traefik.hostname" . }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: traefik
                port:
                  number: 80
              {{- else }}
              serviceName: traefik
              servicePort: 80
              {{- end }}
  tls:
    - hosts: [{{ include "traefik.hostname" . }}]
      secretName: {{ include "traefik.secretname" . }}
