apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-forward-auth-home
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://node5.k8s.cajun.pro:6443
  project: default
  source:
    path: traefik-forward-auth
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-home.yaml
    repoURL: git@github.com:DirtyCajunRice/GitOps-Argo-CD.git
  syncPolicy:
    automated: {}
