apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongodb-silence-among-us
spec:
  version: "4.1.7-v2"
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate
