apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: arrsync-sonarr
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          nodeSelector:
            cajun.pro/cluster-gen: "2"
          containers:
            - name: arrsync-sonarr
              image: itscontained/arrsync:0.2.0-amd64
              envFrom:
                - configMapRef:
                    name: arrsync-sonarr-env
              env:
                - name: ARRSYNC_API_KEY_MASTER
                  valueFrom:
                    secretKeyRef:
                      name: sonarr
                      key: api-key-1080p
                - name: ARRSYNC_API_KEY_SLAVE
                  valueFrom:
                    secretKeyRef:
                      name: sonarr
                      key: api-key-4k
          restartPolicy: OnFailure
