petio-frontend:
  fullnameOverride: "petio"
  image:
    organization: ghcr.io/petio-team
    repository: petio
    tag: fe-latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.priority: "10"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-4@kubernetescrd
    hosts:
      - host: nickflix.io
        paths:
          - path: /petio
            pathType: Prefix
    tls:
      - hosts: [nickflix.io]
        secretName: nickflix-io
    extraIngresses:
      - enabled: true
        nameSuffix: "admin"
        annotations:
          traefik.ingress.kubernetes.io/router.priority: "15"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-0@kubernetescrd
        hosts:
          - host: nickflix.io
            paths:
              - path: /petio/admin
                pathType: Prefix
        tls:
          - hosts: [nickflix.io]
            secretName: nickflix-io
  service:
    port: 80
  persistence:
    type: deployment
    config:
      enabled: false
  nodeSelector:
    cajun.pro/cluster-gen: "2"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 2Gi
petio-backend:
  fullnameOverride: "petio-api"
  image:
    organization: ghcr.io/petio-team
    repository: petio
    tag: be-latest
    pullPolicy: Always
  env:
    REACT_APP_DB_DEFAULT: "mongodb://mongodb-petio.cajun-pro.svc:27017"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.priority: "15"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: nickflix.io
        paths:
          - path: /petio/api
            pathType: Prefix
    tls:
      - hosts: [nickflix.io]
        secretName: nickflix-io
  service:
    port: 7778
  persistence:
    type: deployment
    config:
      enabled: false
  nodeSelector:
    cajun.pro/cluster-gen: "2"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 2Gi
