traefik-forward-auth:
  fullnameOverride: traefik-forward-auth
  traefikForwardAuth:
    cookie:
      domain: "cajun.pro,nickflix.io"
    logging:
      level: debug
      format: json
    providers:
      google:
        enabled: true
  envFrom:
    SECRET:
      name: traefik-forward-auth
      key: secret
    PROVIDERS_GOOGLE_CLIENT_ID:
      name: traefik-forward-auth
      key: google-client-id
    PROVIDERS_GOOGLE_CLIENT_SECRET:
      name: traefik-forward-auth
      key: google-client-secret
    WHITELIST:
      name: traefik-forward-auth
      key: whitelist
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.priority: "50"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-google-auth@kubernetescrd