apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-do
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cert-manager
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
    repoURL: git@github.com:DirtyCajunRice/GitOps-Argo-CD.git
  syncPolicy:
    automated: {}
