apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres-statping
spec:
  version: 11.2-v1
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  authSecret:
    name: postgres
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          app: statping
        interval: 10s
  terminationPolicy: DoNotTerminate
