vault:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: le-production
      hosts:
        - host: vault.cajun.pro
          paths:
            - /
      tls:
        - hosts:
            - vault.cajun.pro
          secretName: vault-cajun-pro
  dataStorage:
    storageClass: file
  ui:
    enabled: true