apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: kubedb-license
spec:
  backendType: vault
  vaultMountPoint: kubernetes-do
  vaultRole: vault-auth
  data:
    - name: key.txt
      key: kv-v2/data/auth/kubedb
      property: license
