apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "15"
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: le-production
  labels:
    app: tautulli-api
  name: tautulli-api
spec:
  rules:
    - host: nickflix.io
      http:
        paths:
          - backend:
              serviceName: tautulli
              servicePort: 8181
            path: /tautulli/api
  tls:
    - hosts:
        - nickflix.io
      secretName: nickflix-io
