apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.middlewares: cajun-pro-organizr-auth-4@kubernetescrd
    cert-manager.io/cluster-issuer: le-production
  labels:
    app: tautulli-base
  name: tautulli-base
spec:
  rules:
    - host: nickflix.io
      http:
        paths:
          - backend:
              serviceName: tautulli
              servicePort: 8181
            path: /tautulli
  tls:
    - hosts:
        - nickflix.io
      secretName: nickflix-io
