conreq:
  fullnameOverride: "conreq"
  image:
    organization: itscontained
    repository: conreq
    tag: alpha-2020-11-3
  env:
    TZ: America/Chicago
    PUID: "1000"
    PGID: "1000"
    DATA_DIR: "/config"
    ALLOWED_HOSTS: "conreq.cajun.pro"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.priority: "10"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: le-production
    tls:
      - hosts: [conreq.cajun.pro]
        secretName: conreq-cajun-pro
    hosts:
      - host: conreq.cajun.pro
        paths:
          - path: /
            pathType: Prefix
  service:
    port: 8000
  persistence:
    type: statefulset
    config:
      accessMode: ReadWriteMany
      size: 10Gi
      storageClass: rook-cephfs
  nodeSelector:
    cajun.pro/cluster-gen: "2"
