cert-manager:
  fullnameOverride: cert-manager
  prometheus:
    servicemonitor:
      enabled: "true"
  installCRDs: true
  volumes:
    - name: aws-credentials
      secret:
        defaultMode: 420
        secretName: aws-creds
  volumeMounts:
    - mountPath: /.aws
      name: aws-credentials
      readOnly: true
raw:
  resources:
    - apiVersion: cert-manager.io/v1alpha2
      kind: ClusterIssuer
      metadata:
        name: le-production
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: nick@cajun.pro
          privateKeySecretRef:
            name: letsencrypt
          solvers:
            - selector:
                dnsZones:
                  - "nickflix.io"
                  - "cajun.pro"
                  - "itscontained.io"
              dns01:
                route53:
                  region: us-east-1
